
string(REGEX REPLACE "(.*)/" "" THIS_FOLDER_NAME "${CMAKE_CURRENT_SOURCE_DIR}")

project (${THIS_FOLDER_NAME})

if (NOT DEFINED MAIN_SCRIPTS_DIR)
	set(MAIN_SCRIPTS_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../scripts)
endif ()

file (STRINGS "${MAIN_SCRIPTS_DIR}/pd-linker-flags.txt" PD_SYM_LINKER_FLAGS)

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../../pd_objects")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")

set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${PD_SYM_LINKER_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${PD_SYM_LINKER_FLAGS}")
